/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 08-18-2009
 * 
 * XDoclet definition:
 * @struts.form name="bonusApplicationForm"
 */
public class BonusApplicationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** contractStartTime property */
	private String contractStartTime;

	/** contractFinishTime property */
	private String contractFinishTime;

	/** assumeCompany property */
	private String assumeCompany;

	/** projectInvestigationReport property */
	private String projectInvestigationReport;

	/** principalB property */
	private String principalB;

	/** contractTestTime property */
	private String contractTestTime;

	/** cooperationCompany property */
	private String cooperationCompany;

	/** projectInvestment property */
	private String projectInvestment;

	/** bonusLevel property */
	private String bonusLevel;
    private FormFile formFile;
	/** projectName property */


	/** principalA property */
	private String principalA;
	private String processid;
	   private String taskid;
	   private String pid;
	   private String pname;
	   private String uid;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the contractStartTime.
	 * @return String
	 */
	public String getContractStartTime() {
		return contractStartTime;
	}

	/** 
	 * Set the contractStartTime.
	 * @param contractStartTime The contractStartTime to set
	 */
	public void setContractStartTime(String contractStartTime) {
		this.contractStartTime = contractStartTime;
	}

	/** 
	 * Returns the contractFinishTime.
	 * @return String
	 */
	public String getContractFinishTime() {
		return contractFinishTime;
	}

	/** 
	 * Set the contractFinishTime.
	 * @param contractFinishTime The contractFinishTime to set
	 */
	public void setContractFinishTime(String contractFinishTime) {
		this.contractFinishTime = contractFinishTime;
	}

	/** 
	 * Returns the assumeCompany.
	 * @return String
	 */
	public String getAssumeCompany() {
		return assumeCompany;
	}

	/** 
	 * Set the assumeCompany.
	 * @param assumeCompany The assumeCompany to set
	 */
	public void setAssumeCompany(String assumeCompany) {
		this.assumeCompany = assumeCompany;
	}

	/** 
	 * Returns the projectInvestigationReport.
	 * @return String
	 */
	public String getProjectInvestigationReport() {
		return projectInvestigationReport;
	}

	/** 
	 * Set the projectInvestigationReport.
	 * @param projectInvestigationReport The projectInvestigationReport to set
	 */
	public void setProjectInvestigationReport(String projectInvestigationReport) {
		this.projectInvestigationReport = projectInvestigationReport;
	}

	/** 
	 * Returns the principalB.
	 * @return String
	 */
	public String getPrincipalB() {
		return principalB;
	}

	/** 
	 * Set the principalB.
	 * @param principalB The principalB to set
	 */
	public void setPrincipalB(String principalB) {
		this.principalB = principalB;
	}

	/** 
	 * Returns the contractTestTime.
	 * @return String
	 */
	public String getContractTestTime() {
		return contractTestTime;
	}

	/** 
	 * Set the contractTestTime.
	 * @param contractTestTime The contractTestTime to set
	 */
	public void setContractTestTime(String contractTestTime) {
		this.contractTestTime = contractTestTime;
	}

	/** 
	 * Returns the cooperationCompany.
	 * @return String
	 */
	public String getCooperationCompany() {
		return cooperationCompany;
	}

	/** 
	 * Set the cooperationCompany.
	 * @param cooperationCompany The cooperationCompany to set
	 */
	public void setCooperationCompany(String cooperationCompany) {
		this.cooperationCompany = cooperationCompany;
	}

	/** 
	 * Returns the projectInvestment.
	 * @return String
	 */
	public String getProjectInvestment() {
		return projectInvestment;
	}

	/** 
	 * Set the projectInvestment.
	 * @param projectInvestment The projectInvestment to set
	 */
	public void setProjectInvestment(String projectInvestment) {
		this.projectInvestment = projectInvestment;
	}

	/** 
	 * Returns the bonusLevel.
	 * @return String
	 */
	public String getBonusLevel() {
		return bonusLevel;
	}

	/** 
	 * Set the bonusLevel.
	 * @param bonusLevel The bonusLevel to set
	 */
	public void setBonusLevel(String bonusLevel) {
		this.bonusLevel = bonusLevel;
	}

	/** 
	 * Returns the projectName.
	 * @return String
	 */
	
	/** 
	 * Returns the principalA.
	 * @return String
	 */
	public String getPrincipalA() {
		return principalA;
	}

	/** 
	 * Set the principalA.
	 * @param principalA The principalA to set
	 */
	public void setPrincipalA(String principalA) {
		this.principalA = principalA;
	}
	public String getProcessid(){
		return processid;
	}
	public void setProcessid(String processid){
		this.processid=processid;
	}
	public String getTaskid(){
		return taskid;
	}
	public void setTaskid(String taskid){
		this.taskid=taskid;
	}
	public String getPid(){
		return pid;
	}
	public void setPid(String pid){
		this.pid=pid;
	}
	public String getPname(){
		return pname;
	}
	public void setPname(String pname){
		this.pname=pname;
	}
	public String getUid(){
		return uid;
	}
	public void setUid(String uid){
		this.uid=uid;
	}

	public FormFile getFormFile() {
		return formFile;
	}

	public void setFormFile(FormFile formFile) {
		this.formFile = formFile;
	}
}