/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2009
 * 
 * XDoclet definition:
 * @struts.form name="techForm"
 */
public class TechForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** setime property */
	private String setime;

	/** sname property */
	private String sname;

	/** suname property */
	private String suname;

	/** scomp property */
	private String scomp;

	/** smodle property */
	private String smodle;

	/** sfact property */
	//private String sfact;

	/** stype property */
	private String stype;

	/** stime property */
	private String stime;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the setime.
	 * @return String
	 */
	public String getSetime() {
		return setime;
	}

	/** 
	 * Set the setime.
	 * @param setime The setime to set
	 */
	public void setSetime(String setime) {
		this.setime = setime;
	}

	/** 
	 * Returns the sname.
	 * @return String
	 */
	public String getSname() {
		return sname;
	}

	/** 
	 * Set the sname.
	 * @param sname The sname to set
	 */
	public void setSname(String sname) {
		this.sname = sname;
	}

	/** 
	 * Returns the suname.
	 * @return String
	 */
	public String getSuname() {
		return suname;
	}

	/** 
	 * Set the suname.
	 * @param suname The suname to set
	 */
	public void setSuname(String suname) {
		this.suname = suname;
	}

	/** 
	 * Returns the scomp.
	 * @return String
	 */
	public String getScomp() {
		return scomp;
	}

	/** 
	 * Set the scomp.
	 * @param scomp The scomp to set
	 */
	public void setScomp(String scomp) {
		this.scomp = scomp;
	}

	/** 
	 * Returns the smodle.
	 * @return String
	 */
	public String getSmodle() {
		return smodle;
	}

	/** 
	 * Set the smodle.
	 * @param smodle The smodle to set
	 */
	public void setSmodle(String smodle) {
		this.smodle = smodle;
	}

	/** 
	 * Returns the sfact.
	 * @return String
	 */
	//ublic String getSfact() {
		//return sfact;
	//}

	/** 
	 * Set the sfact.
	 * @param sfact The sfact to set
	 */
	//public void setSfact(String sfact) {
	//	this.sfact = sfact;
	//}

	/** 
	 * Returns the stype.
	 * @return String
	 */
	public String getStype() {
		return stype;
	}

	/** 
	 * Set the stype.
	 * @param stype The stype to set
	 */
	public void setStype(String stype) {
		this.stype = stype;
	}

	/** 
	 * Returns the stime.
	 * @return String
	 */
	public String getStime() {
		return stime;
	}

	/** 
	 * Set the stime.
	 * @param stime The stime to set
	 */
	public void setStime(String stime) {
		this.stime = stime;
	}
}