/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 08-18-2009
 * 
 * XDoclet definition:
 * @struts.form name="testApplicationForm"
 */
public class TestApplicationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** projectSchedule property */
	private String projectSchedule;

	/** projectExecutor property */
	private String projectExecutor;

	
	/** paymentSituation property */
	private String paymentSituation;
	 private String processid;
	   private String taskid;
	   private String pid;
	   private String pname;
	   private String uid;
	  private FormFile formFile;
    
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the projectSchedule.
	 * @return String
	 */
	public String getProjectSchedule() {
		return projectSchedule;
	}

	/** 
	 * Set the projectSchedule.
	 * @param projectSchedule The projectSchedule to set
	 */
	public void setProjectSchedule(String projectSchedule) {
		this.projectSchedule = projectSchedule;
	}

	/** 
	 * Returns the projectExecutor.
	 * @return String
	 */
	public String getProjectExecutor() {
		return projectExecutor;
	}

	/** 
	 * Set the projectExecutor.
	 * @param projectExecutor The projectExecutor to set
	 */
	public void setProjectExecutor(String projectExecutor) {
		this.projectExecutor = projectExecutor;
	}

	/** 
	 * Returns the projectName.
	 * @return String
	 */
	

	/** 
	 * Returns the paymentSituation.
	 * @return String
	 */
	public String getPaymentSituation() {
		return paymentSituation;
	}

	/** 
	 * Set the paymentSituation.
	 * @param paymentSituation The paymentSituation to set
	 */
	public void setPaymentSituation(String paymentSituation) {
		this.paymentSituation = paymentSituation;
	}
	public String getProcessid(){
		return processid;
	}
	public void setProcessid(String processid){
		this.processid=processid;
	}
	public String getTaskid(){
		return taskid;
	}
	public void setTaskid(String taskid){
		this.taskid=taskid;
	}
	public String getPid(){
		return pid;
	}
	public void setPid(String pid){
		this.pid=pid;
	}
	public String getPname(){
		return pname;
	}
	public void setPname(String pname){
		this.pname=pname;
	}
	public String getUid(){
		return uid;
	}
	public void setUid(String uid){
		this.uid=uid;
	}

	public FormFile getFormFile() {
		return formFile;
	}

	public void setFormFile(FormFile formFile) {
		this.formFile = formFile;
	}
}