/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2009
 * 
 * XDoclet definition:
 * @struts.form name="uploadForm"
 */
public class UploadForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** loadurl property */
	private String loadurl;

	/** loadname property */
	private String loadname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the loadurl.
	 * @return String
	 */
	public String getLoadurl() {
		return loadurl;
	}

	/** 
	 * Set the loadurl.
	 * @param loadurl The loadurl to set
	 */
	public void setLoadurl(String loadurl) {
		this.loadurl = loadurl;
	}

	/** 
	 * Returns the loadname.
	 * @return String
	 */
	public String getLoadname() {
		return loadname;
	}

	/** 
	 * Set the loadname.
	 * @param loadname The loadname to set
	 */
	public void setLoadname(String loadname) {
		this.loadname = loadname;
	}
}