/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-14-2009
 * 
 * XDoclet definition:
 * @struts.form name="userForm"
 */
public class UserForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** reftype property */
	private String reftype;

	/** refyear property */
	private String refyear;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the reftype.
	 * @return String
	 */
	public String getReftype() {
		return reftype;
	}

	/** 
	 * Set the reftype.
	 * @param reftype The reftype to set
	 */
	public void setReftype(String reftype) {
		this.reftype = reftype;
	}

	/** 
	 * Returns the refyear.
	 * @return String
	 */
	public String getRefyear() {
		return refyear;
	}

	/** 
	 * Set the refyear.
	 * @param refyear The refyear to set
	 */
	public void setRefyear(String refyear) {
		this.refyear = refyear;
	}
}