/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2009
 * 
 * XDoclet definition:
 * @struts.form name="user1Form"
 */
public class User1Form extends ActionForm {
	/*
	 * Generated fields
	 */

	/** ufact property */
	private String ufact;

	/** umonth property */
	private String umonth;

	/** umodle property */
	//private String umodle;

	/** ueyear property */
	private String ueyear;

	/** ueday property */
	private String ueday;

	/** uyear property */
	private String uyear;

	/** uemonth property */
	private String uemonth;

	/** uday property */
	private String uday;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the ufact.
	 * @return String
	 */
	public String getUfact() {
		return ufact;
	}

	/** 
	 * Set the ufact.
	 * @param ufact The ufact to set
	 */
	public void setUfact(String ufact) {
		this.ufact = ufact;
	}

	/** 
	 * Returns the umonth.
	 * @return String
	 */
	public String getUmonth() {
		return umonth;
	}

	/** 
	 * Set the umonth.
	 * @param umonth The umonth to set
	 */
	public void setUmonth(String umonth) {
		this.umonth = umonth;
	}

	/** 
	 * Returns the umodle.
	 * @return String
	 */
	//public String getUmodle() {
	//	return umodle;
	//}

	/** 
	 * Set the umodle.
	 * @param umodle The umodle to set
	 */
	//public void setUmodle(String umodle) {
		//this.umodle = umodle;
	//}

	/** 
	 * Returns the ueyear.
	 * @return String
	 */
	public String getUeyear() {
		return ueyear;
	}

	/** 
	 * Set the ueyear.
	 * @param ueyear The ueyear to set
	 */
	public void setUeyear(String ueyear) {
		this.ueyear = ueyear;
	}

	/** 
	 * Returns the ueday.
	 * @return String
	 */
	public String getUeday() {
		return ueday;
	}

	/** 
	 * Set the ueday.
	 * @param ueday The ueday to set
	 */
	public void setUeday(String ueday) {
		this.ueday = ueday;
	}

	/** 
	 * Returns the uyear.
	 * @return String
	 */
	public String getUyear() {
		return uyear;
	}

	/** 
	 * Set the uyear.
	 * @param uyear The uyear to set
	 */
	public void setUyear(String uyear) {
		this.uyear = uyear;
	}

	/** 
	 * Returns the uemonth.
	 * @return String
	 */
	public String getUemonth() {
		return uemonth;
	}

	/** 
	 * Set the uemonth.
	 * @param uemonth The uemonth to set
	 */
	public void setUemonth(String uemonth) {
		this.uemonth = uemonth;
	}

	/** 
	 * Returns the uday.
	 * @return String
	 */
	public String getUday() {
		return uday;
	}

	/** 
	 * Set the uday.
	 * @param uday The uday to set
	 */
	public void setUday(String uday) {
		this.uday = uday;
	}
}