/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2009
 * 
 * XDoclet definition:
 * @struts.form name="userchangeForm"
 */
public class UserchangeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userclass property */
	private String userclass;

	/** userID property */
	private String userID;

	/** usermodle property */
	private String usermodle;

	/** useraddress property */
	private String useraddress;

	/** usergroup property */
	private String usergroup;

	/** username property */
	private String username;

	/** userpwd property */
	private String userpwd;

	/** name property */
	private String name;

	/** userphone property */
	private String userphone;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userclass.
	 * @return String
	 */
	public String getUserclass() {
		return userclass;
	}

	/** 
	 * Set the userclass.
	 * @param userclass The userclass to set
	 */
	public void setUserclass(String userclass) {
		this.userclass = userclass;
	}

	/** 
	 * Returns the userID.
	 * @return String
	 */
	public String getUserID() {
		return userID;
	}

	/** 
	 * Set the userID.
	 * @param userID The userID to set
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/** 
	 * Returns the usermodle.
	 * @return String
	 */
	public String getUsermodle() {
		return usermodle;
	}

	/** 
	 * Set the usermodle.
	 * @param usermodle The usermodle to set
	 */
	public void setUsermodle(String usermodle) {
		this.usermodle = usermodle;
	}

	/** 
	 * Returns the useraddress.
	 * @return String
	 */
	public String getUseraddress() {
		return useraddress;
	}

	/** 
	 * Set the useraddress.
	 * @param useraddress The useraddress to set
	 */
	public void setUseraddress(String useraddress) {
		this.useraddress = useraddress;
	}

	/** 
	 * Returns the usergroup.
	 * @return String
	 */
	public String getUsergroup() {
		return usergroup;
	}

	/** 
	 * Set the usergroup.
	 * @param usergroup The usergroup to set
	 */
	public void setUsergroup(String usergroup) {
		this.usergroup = usergroup;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the userpwd.
	 * @return String
	 */
	public String getUserpwd() {
		return userpwd;
	}

	/** 
	 * Set the userpwd.
	 * @param userpwd The userpwd to set
	 */
	public void setUserpwd(String userpwd) {
		this.userpwd = userpwd;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the userphone.
	 * @return String
	 */
	public String getUserphone() {
		return userphone;
	}

	/** 
	 * Set the userphone.
	 * @param userphone The userphone to set
	 */
	public void setUserphone(String userphone) {
		this.userphone = userphone;
	}
}