/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chinasofti.dao.ProjectDAO;
import com.chinasofti.service.IBonusApproveService;
import com.chinasofti.web.struts.form.BonusApproveForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/bonusApprove" name="bonusApproveForm" input="/approveSystem/bonusApprove2.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/approveSystem/submissionSuccess.jsp"
 */
public class BonusApproveAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private ProjectDAO projectDAO;
	private IBonusApproveService bonusApproveService;
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BonusApproveForm bonusApproveForm = (BonusApproveForm) form;// TODO Auto-generated method stub
		String pathString=bonusApproveService.save(bonusApproveForm);
		
	
		return mapping.findForward(pathString);
	}
	
	public void setProjectDAO(ProjectDAO projectDAO) {
		this.projectDAO = projectDAO;
	}
	
	public void setBonusApproveService(IBonusApproveService bonusApproveService) {
		this.bonusApproveService = bonusApproveService;
	}
}