/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import com.chinasofti.dao.ProjectDAO;

import com.chinasofti.service.ILixiangshenpiService;



import com.chinasofti.web.struts.form.LixiangshenpiForm;


/** 
 * MyEclipse Struts
 * Creation date: 08-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/lixiangshenpi" name="lixiangshenpiForm" input="/approveSystem/settingUpApprove2.jsp" scope="request" validate="true"
 * @struts.action-forward name="sucess" path="/approveSystem/submissionSucess.jsp"
 */
public class LixiangshenpiAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	
	private ILixiangshenpiService lixiangshenpiService;
	private ProjectDAO projectDAO;
	
	
	public void setLixiangshenpiService(ILixiangshenpiService lixiangshenpiService){
		this.lixiangshenpiService=lixiangshenpiService;
	}
	public void setProjectDAO(ProjectDAO projectDAO){
		this.projectDAO=projectDAO;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LixiangshenpiForm lixiangshenpiForm = (LixiangshenpiForm) form;// TODO Auto-generated method stub
		
		String isDone=lixiangshenpiService.save(lixiangshenpiForm);
		return mapping.findForward(isDone);
	}
}