/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.chinasofti.web.struts.form.UploadForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2009
 * 
 * XDoclet definition:
 * @struts.action path="/loading" name="uploadForm" input="/technologymanagementsys/tab/loadadd.jsp" scope="request" validate="true"
 * @struts.action-forward name="loading" path="/technologymanagementsys/tab/uploadadd.jsp"
 */
public class LoadingAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UploadForm uploadForm = (UploadForm) form;// TODO Auto-generated method stub
		return mapping.findForward("loading");
	}
}