/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.chinasofti.web.struts.form.LoadchangeForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2009
 * 
 * XDoclet definition:
 * @struts.action path="/loadchangeback" name="loadchangeForm" input="/technologymanagementsys/tab/loadchange.jsp" scope="request" validate="true"
 * @struts.action-forward name="back" path="/technologymanagementsys/loadchange.jsp"
 */
public class LoadchangebackAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoadchangeForm loadchangeForm = (LoadchangeForm) form;// TODO Auto-generated method stub
		return mapping.findForward("back");
	}
}