/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chinasofti.dao.ProjectDAO;
import com.chinasofti.dao.UserDAO;
import com.chinasofti.service.ILoginService;
import com.chinasofti.service.IMService;

import com.chinasofti.web.struts.form.LoginForm;


/** 
 * MyEclipse Struts
 * Creation date: 08-16-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" input="/login/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private ILoginService loginService;
	private IMService mService;
	private UserDAO userDAO;
	private ProjectDAO projectDAO;
	
	public void setLoginService(ILoginService loginService){
		this.loginService=loginService;
	}
	public void setMService(IMService mService){
		this.mService=mService;
	}
	public void setUserDAO(UserDAO userDAO){
		this.userDAO=userDAO;
	}
	public void setProjectDAO(ProjectDAO projectDAO){
		this.projectDAO=projectDAO;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
	System.out.println(loginForm.getUsername());
		
		//ApplicationContext cx = new FileSystemXmlApplicationContext("E:/apache-tomcat-6.0.14/webapps/technologyapprove/WEB-INF/applicationContext.xml");
	
		
		request.getSession().setAttribute("name", loginForm.getUsername());
		int id=loginService.getUserId(loginForm);
		System.out.println(id);
		//根据登录名，把用户id、真实姓名载入到session对象中
		request.getSession().setAttribute("uid", String.valueOf(id));
		request.getSession().setAttribute("realname", loginService.getRealName(loginForm));
		request.getSession().setAttribute("class", String.valueOf(loginService.getLoginClass(loginForm)));
	    
		return mapping.findForward(loginService.getLoginInfo(loginForm));
	}
}