/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chinasofti.dao.ProjectDAO;
import com.chinasofti.service.IProductsAppraisalApproveService;
import com.chinasofti.web.struts.form.ProductsAppraisalApproveForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/productsAppraisalApprove" name="productsAppraisalApproveForm" input="/approveSystem/productsAppraisalApprove2.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/approveSystem/submissionSuccess.jsp"
 */
public class ProductsAppraisalApproveAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private IProductsAppraisalApproveService productsAppraisalApproveService;
	private ProjectDAO projectDAO;
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ProductsAppraisalApproveForm productsAppraisalApproveForm = (ProductsAppraisalApproveForm) form;// TODO Auto-generated method stub
	    String pathString=productsAppraisalApproveService.save(productsAppraisalApproveForm);
		return mapping.findForward(pathString);
	}
	
	public void setProductsAppraisalApproveService(
			IProductsAppraisalApproveService productsAppraisalApproveService) {
		this.productsAppraisalApproveService = productsAppraisalApproveService;
	}
	
	public void setProjectDAO(ProjectDAO projectDAO) {
		this.projectDAO = projectDAO;
	}
}