/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.chinasofti.web.struts.form.User1Form;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2009
 * 
 * XDoclet definition:
 * @struts.action path="/searchback1" name="user1Form" input="/usersys/tab/search1add.jsp" scope="request" validate="true"
 * @struts.action-forward name="search1backup" path="/usersys/ref1left.jsp"
 */
public class Searchback1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		User1Form user1Form = (User1Form) form;// TODO Auto-generated method stub
		return mapping.findForward("searchbackup1");
	}
}