/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chinasofti.service.ITechProService;
import com.chinasofti.service.impl.GetService;
import com.chinasofti.web.struts.form.TechForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2009
 * 
 * XDoclet definition:
 * @struts.action input="/usersys/tab/searchadd.jsp" validate="true"
 * @struts.action-forward name="searchbackup" path="/usersys/searchleft.jsp"
 */
public class SearchbackAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		
		return mapping.findForward("searchbackup");
	}
}