/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chinasofti.domain.Project;
import com.chinasofti.service.ITechProService;
import com.chinasofti.service.impl.GetService;
import com.chinasofti.web.struts.form.TechForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2009
 * 
 * XDoclet definition:
 * @struts.action path="/tech" name="techForm" input="/form/tech.jsp" scope="request" validate="true"
 */
public class TechAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TechForm techForm = (TechForm) form;// TODO Auto-generated method stub
		String scomp = techForm.getScomp();
		
		String smodle = techForm.getSmodle();
		String sname = techForm.getSname();
		String suname = techForm.getSuname();
		String stype = techForm.getStype();
		String stime = techForm.getStime();
		String setime = techForm.getSetime();
		request.getSession().setAttribute("tech", sname);
		//System.out.println("sdjcbgjkervgjklfjklrtkl" + sname);
		ITechProService tps = GetService.getTechProService();
		List list = tps.search(techForm);
		//System.out.println("sdjcbgjkervgjklfjklrtkl" + list.size());
		//Project pro = (Project)list.get(0);
		request.getSession().setAttribute("list", list);
		return mapping.findForward("searchadd");
	}
}