/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chinasofti.dao.ProjectDAO;
import com.chinasofti.service.ITestApproveService;
import com.chinasofti.web.struts.form.TestApproveForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-18-2009
 * 
 * XDoclet definition:
 * @struts.action path="/testApprove" name="testApproveForm" input="/approveSystem/testApprove2.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/approveSystem/submissionSuccess.jsp"
 */
public class TestApproveAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	private ProjectDAO projectDAO;
	private ITestApproveService testApproveService;
	public void setProjectDAO(ProjectDAO projectDAO){
		this.projectDAO=projectDAO;
	}
	public void setTestApproveService(ITestApproveService testApproveService){
		this.testApproveService=testApproveService;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TestApproveForm testApproveForm = (TestApproveForm) form;// TODO Auto-generated method stub
	    String pathString=testApproveService.save(testApproveForm);
		return mapping.findForward(pathString);
	}
}