/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chinasofti.service.IUserService;
import com.chinasofti.service.impl.GetService;
import com.chinasofti.web.struts.form.TmuserForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-16-2009
 * 
 * XDoclet definition:
 * @struts.action path="/tmuser" name="tmuserForm" input="/technologymanagementsys/useradd.jsp" scope="request" validate="true"
 */
public class TmuserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TmuserForm tmuserForm = (TmuserForm) form;// TODO Auto-generated method stub
		String userID = tmuserForm.getUserID();
		String username = tmuserForm.getUsername();
		String userpwd = tmuserForm.getUserpwd();
		String name = tmuserForm.getName();
		String usergroup = tmuserForm.getUsergroup();
		String userclass = tmuserForm.getUserclass();
		String usermodle = tmuserForm.getUsermodle();
		String useraddres = tmuserForm.getUseraddress();
		String userphone = tmuserForm.getUserphone();
		String userString = "";
		String modle = "";
		if(usergroup.equals("1")){
			userString = "worker";
		}
		if(usergroup.equals("2")){
			userString = "chief1";
		}
		if(usergroup.equals("3")){
			userString = "chief2";
		}
		if(usergroup.equals("4")){
			userString = "chief3";
		}
		if(usergroup.equals("5")){
			userString = "chief4";
		}
		if(usergroup.equals("6")){
			userString = "chief5";
		}
		if(usergroup.equals("7")){
			userString = "management";
		}
		if(usergroup.equals("8")){
			userString = "admin";
		}
		
		if(usermodle.equals("1")){
			modle  = "分公司A";
		}
		if(usermodle.equals("2")){
			modle = "分公司B";
		}
		if(usermodle.equals("3")){
			modle = "分公司C";
		}
		
		
		request.getSession().setAttribute("userID", userID);
		request.getSession().setAttribute("username", username);
		request.getSession().setAttribute("userpwd", userpwd);
		request.getSession().setAttribute("name", name);
		request.getSession().setAttribute("usergroup", userString);
		request.getSession().setAttribute("userclass", userclass);
		request.getSession().setAttribute("usermodle", modle);
		request.getSession().setAttribute("useraddres", useraddres);
		request.getSession().setAttribute("userphone", userphone);
		
		IUserService us = GetService.getUserService();
		us.Save(us.User(tmuserForm));
		
		return mapping.findForward("useradd");
	}
}