/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinasofti.web.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.chinasofti.service.ITechProService;
import com.chinasofti.service.impl.GetService;
import com.chinasofti.web.struts.form.User1Form;
import com.sun.accessibility.internal.resources.accessibility;
import com.sun.java_cup.internal.internal_error;

/** 
 * MyEclipse Struts
 * Creation date: 08-15-2009
 * 
 * XDoclet definition:
 * @struts.action path="/user1" name="user1Form" input="/form/user1.jsp" scope="request" validate="true"
 */
public class User1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		User1Form user1Form = (User1Form) form;// TODO Auto-generated method stub
		
	
		String uyear = user1Form.getUyear();
		String umonth = user1Form.getUmonth();
		String uday = user1Form.getUday();
		String ueyear = user1Form.getUeyear();
		String uemonth = user1Form.getUemonth();
		String ueday = user1Form.getUeday();
		String udate = uyear+umonth+uday;
		String uedate = ueyear+uemonth+ueday;
		request.getSession().setAttribute("udate", udate);
		request.getSession().setAttribute("uedate", uedate);
		List<String> a= new ArrayList<String>();
		a.add("分公司A");
		a.add("分公司B");
		a.add("分公司C");
		ITechProService tps = GetService.getTechProService();
		int[] wanted = null;
	    wanted=	tps.schForBlock(user1Form);
		
		request.getSession().setAttribute("wanted", wanted);
		request.getSession().setAttribute("comp", a);
		return mapping.findForward("search1add");
	}
}